---
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./config:/config
      - $HOME/Media/Series:/tv
      - $HOME/Downloads:/downloads
    networks:
      - prowlarr_default
    ports:
      - 8989:8989
    restart: unless-stopped
networks:
  prowlarr_default:
    external: true
