---
services:
  kavita:
    image: lscr.io/linuxserver/kavita:latest
    container_name: kavita
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${DOCKER_PERSISTENT_STORAGE_DIR}/kavita:/config
      - ${BOOKS_DIR}:/books #optional
    ports:
      - 5968:5000
    restart: unless-stopped
