---
services:
  guacd:
    image: guacamole/guacd:latest
    container_name: guacd
    restart: unless-stopped
  guacamole:
    image: guacamole/guacamole:latest
    container_name: guacamole
    environment:
      - GUACD_HOSTNAME=guacd
      - MYSQL_HOSTNAME=mariadb
      - MYSQL_DATABASE=guacamole
      - MYSQL_USER=guacamole
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - TOTP_ENABLED=true
    networks:
      - mariadb_default
    ports:
      - 8080:8080
    restart: unless-stopped
networks:
  mariadb_default:
    external: true
