---
services:
  dashdot:
    image: mauricenino/dashdot:latest
    container_name: dashdot
    privileged: true
    environment:
      DASHDOT_ALWAYS_SHOW_PERCENTAGES: true
      DASHDOT_SHOW_HOST: true
      DASHDOT_CUSTOM_HOST: 'homelab'
      DASHDOT_ENABLE_CPU_TEMPS: true
    volumes:
      - /:/mnt/host:ro
    ports:
      - 3001:3001
    restart: unless-stopped
