---
services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PASSWORD=${CODE_SERVER_PASSWORD}
      # - HASHED_PASSWORD= #optional
      # - SUDO_PASSWORD= #optional
      # - SUDO_PASSWORD_HASH= #optional
      # - PROXY_DOMAIN= #optional
      # - DEFAULT_WORKSPACE= #optional
    volumes:
      - ./config:/config
      - ~:/workspaces/home
    ports:
      - 8443:8443
    restart: unless-stopped
