---
services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - $HOME/.containers/code-server/config:/config
      - $HOME/Syncthing/Notes:/notes
    ports:
      - 8443:8443
    restart: unless-stopped
