---
services:
  mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      # - MYSQL_DATABASE= #optional
      # - MYSQL_USER= #optional, make sure not to use 'root'.
      # - MYSQL_PASSWORD= #optional
      # - REMOTE_SQL= #optional
    volumes:
      - ./config:/config
    networks:
      - default
    ports:
      - 3306:3306
    restart: unless-stopped
networks:
  default:
    driver: bridge
