---
services:
  homeassistant:
    image: lscr.io/linuxserver/homeassistant:latest
    container_name: homeassistant
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DOCKER_MODS=linuxserver/mods:homeassistant-hacs
    volumes:
      - ${DOCKER_PERSISTENT_STORAGE_DIR}/homeassistant:/config
      - /var/run/dbus:/var/run/dbus:ro
    network_mode: host
    ports:
      - 8123:8123
    cap_add:
      - NET_ADMIN
      - NET_RAW
    # devices:
    #   - /path/to/device:/path/to/device #optional
    restart: unless-stopped
