---
version: "3"
services:
  flatnotes:
    container_name: flatnotes
    image: dullage/flatnotes:latest
    environment:
      PUID: 0
      PGID: 0
      FLATNOTES_AUTH_TYPE: "none"
    volumes:
      - "$HOME/syncthing/Notes:/data"
      - "$HOME/.containers/flatnotes/config:/data/.flatnotes"
    ports:
      - "8080:8080"
    restart: unless-stopped