---
services:
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./config:/config
      - $HOME/Media/Music:/music #optional
      - $HOME/Downloads:/downloads #optional
    networks:
      - prowlarr_default
    ports:
      - 8686:8686
    restart: unless-stopped
networks:
  prowlarr_default:
    external: true
