---
services:
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${DOCKER_PERSISTENT_STORAGE_DIR}/lidarr:/config
      - ${MUSIC_DIR}:/music #optional
      - ${DOWNLOADS_DIR}:/downloads #optional
    networks:
      - prowlarr_default
    ports:
      - 8686:8686
    restart: unless-stopped
networks:
  prowlarr_default:
    external: true
