---
services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - USER=${TRANSMISSION_USER}
      - PASS=${TRANSMISSION_PASSWORD}
      # - WHITELIST= #optional
      # - PEERPORT= #optional
      # - HOST_WHITELIST= #optional
      # - TRANSMISSION_WEB_HOME= #optional
      - DOCKER_MODS=linuxserver/mods:transmission-floodui
    volumes:
      - ${DOCKER_PERSISTENT_STORAGE_DIR}/transmission:/config
      - ${DOWNLOADS_DIR}/Transmission:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
