---
services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${DOCKER_PERSISTENT_STORAGE_DIR}/prowlarr:/config
    networks:
      - default
    ports:
      - 9696:9696
    restart: unless-stopped
networks:
  default:
    driver: bridge
