---
title: "homelab"
subtitle: "Homer"
icon: "fas fa-flask"
header: true
footer: false
columns: "auto"
connectivityCheck: true
services:
  - name: "DevOps"
    icon: "fas fa-tools"
    items:
      - name: "Code Server"
        logo: "assets/logos/code-server.png"
        subtitle: "Web-based Coding Environment"
        url: "http://127.0.0.1:8443"
      - name: "Guacamole"
        logo: "assets/logos/guacamole.png"
        subtitle: "Clientless Remote Desktop Gateway"
        url: "http://127.0.0.1:8080"

  - name: "Home Automation"
    icon: "fas fa-home"
    items:
      - name: "Homeassistant"
        logo: "assets/logos/home-assistant.png"
        subtitle: "Smart Home Management"
        url: "http://127.0.0.1:8123"

  - name: "Media Server"
    icon: "fas fa-video"
    items:
      - name: "Jellyfin"
        logo: "assets/logos/jellyfin.png"
        subtitle: "Free Media Server Software"
        url: "http://127.0.0.1:8096"

  - name: "Media Management"
    icon: "fas fa-film"
    items:
      - name: "Bazarr"
        logo: "assets/logos/bazarr.png"
        subtitle: "Subtitle Management"
        url: "http://127.0.0.1:6767"
      - name: "Jellyseerr"
        logo: "assets/logos/jellyseerr.png"
        subtitle: "Discovery and Requests Management"
        url: "http://127.0.0.1:5055"
      - name: "Lidarr"
        logo: "assets/logos/lidarr.png"
        subtitle: "Music Library Management"
        url: "http://127.0.0.1:8686"
      - name: "Radarr"
        logo: "assets/logos/radarr.png"
        subtitle: "Movie Library Management"
        url: "http://127.0.0.1:7878"
      - name: "Sonarr"
        logo: "assets/logos/sonarr.png"
        subtitle: "TV Series Library Management"
        url: "http://127.0.0.1:8989"

  - name: "Cloud & File Management"
    icon: "fas fa-cloud"
    items:
      - name: "Nextcloud"
        logo: "assets/logos/nextcloud.png"
        subtitle: "Self-hosted Cloud Storage"
        url: "https://127.0.0.1:443"
      - name: "Syncthing"
        logo: "assets/logos/syncthing.png"
        subtitle: "Continuous File Synchronization"
        url: "http://127.0.0.1:8384"

  - name: "Download Management"
    icon: "fas fa-download"
    items:
      - name: "Prowlarr"
        logo: "assets/logos/prowlarr.png"
        subtitle: "Indexer Management"
        url: "http://127.0.0.1:9696"
      - name: "Transmission"
        logo: "assets/logos/transmission.png"
        subtitle: "Fast and Lightweight BitTorrent Client"
        url: "http://127.0.0.1:9091"
