---
title: "homelab"
subtitle: "Homer"
icon: "fas fa-flask"
header: true
footer: false
columns: "auto"
connectivityCheck: true
services:
  - name: "DevOps"
    icon: "fas fa-tools"
    items:
      - name: "Code Server"
        logo: "assets/logos/code-server.png"
        subtitle: "Web-based Coding Environment"
        url: "http://192.168.192.100:8443"
      - name: "Dash."
        logo: "assets/logos/dashdot.png"
        subtitle: "Modern Server Dashboard"
        url: "http://192.168.192.100:3001"
      - name: "Guacamole"
        logo: "assets/logos/guacamole.png"
        subtitle: "Clientless Remote Desktop Gateway"
        url: "http://192.168.192.100:8080/guacamole"

  - name: "Home Automation"
    icon: "fas fa-home"
    items:
      - name: "Homeassistant"
        logo: "assets/logos/home-assistant.png"
        subtitle: "Smart Home Management"
        url: "http://192.168.192.100:8123"

  - name: "Media Server"
    icon: "fas fa-video"
    items:
      - name: "Jellyfin"
        logo: "assets/logos/jellyfin.png"
        subtitle: "Free Media Server Software"
        url: "http://192.168.192.100:8096"

  - name: "Media Management"
    icon: "fas fa-film"
    items:
      - name: "Bazarr"
        logo: "assets/logos/bazarr.png"
        subtitle: "Subtitle Management"
        url: "http://192.168.192.100:6767"
      - name: "Jellyseerr"
        logo: "assets/logos/jellyseerr.png"
        subtitle: "Discovery and Requests Management"
        url: "http://192.168.192.100:5055"
      - name: "Lidarr"
        logo: "assets/logos/lidarr.png"
        subtitle: "Music Library Management"
        url: "http://192.168.192.100:8686"
      - name: "Radarr"
        logo: "assets/logos/radarr.png"
        subtitle: "Movie Library Management"
        url: "http://192.168.192.100:7878"
      - name: "Sonarr"
        logo: "assets/logos/sonarr.png"
        subtitle: "TV Series Library Management"
        url: "http://192.168.192.100:8989"

  - name: "Cloud & File Management"
    icon: "fas fa-cloud"
    items:
      - name: "Nextcloud"
        logo: "assets/logos/nextcloud.png"
        subtitle: "Self-hosted Cloud Storage"
        url: "https://192.168.192.100:443"
      - name: "Syncthing"
        logo: "assets/logos/syncthing.png"
        subtitle: "Continuous File Synchronization"
        url: "http://192.168.192.100:8384"

  - name: "Download Management"
    icon: "fas fa-download"
    items:
      - name: "Prowlarr"
        logo: "assets/logos/prowlarr.png"
        subtitle: "Indexer Management"
        url: "http://192.168.192.100:9696"
      - name: "Transmission"
        logo: "assets/logos/transmission.png"
        subtitle: "Fast and Lightweight BitTorrent Client"
        url: "http://192.168.192.100:9091"

  - name: "Gaming"
    icon: "fas fa-gamepad"
    items:
      - name: "Ownfoil"
        logo: "assets/logos/ownfoil.png"
        subtitle: "NX Shop and Library Management"
        url: "http://192.168.192.100:8465"
