---
services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DOCKER_MODS=linuxserver/mods:nextcloud-memories | linuxserver/mods:nextcloud-mediadc | linuxserver/mods:nextcloud-notify-push
    volumes:
      - ${NEXTCLOUD_DIR}/config:/config
      - ${NEXTCLOUD_DIR}/data:/data
    networks:
      - mariadb_default
    ports:
      - 443:443
    restart: unless-stopped
  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - ${NEXTCLOUD_DIR}/redis:/data
    networks:
      - mariadb_default
    restart: unless-stopped
  collabora:
    image: collabora/code:latest
    container_name: collabora
    # environment:
    #   - domain= #optional
    #   - username= #optional
    #   - password= #optional
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - mariadb_default
    ports:
      - 9980:9980
    cap_add:
      - MKNOD
    restart: unless-stopped
  imaginary:
    image: h2non/imaginary
    container_name: imaginary
    command: -concurrency 50 -enable-url-source
    # environment:
    #   - PORT= #optional
    networks:
      - mariadb_default
    ports:
      - 9000:9000
    cap_add:
      - SYS_NICE
    restart: unless-stopped
networks:
  mariadb_default:
    external: true
