---
services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DOCKER_MODS=linuxserver/mods:nextcloud-memories | linuxserver/mods:nextcloud-mediadc
    volumes:
      - /mnt/Nextcloud/config:/config
      - /mnt/Nextcloud/data:/data
    networks:
      - mariadb_default
    ports:
      - 443:443
    restart: unless-stopped

networks:
  mariadb_default:
    external: true
