---
services:
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Etc/UTC
      # - PORT= #optional
    volumes:
      - ${DOCKER_PERSISTENT_STORAGE_DIR}/jellyseerr:/app/config
    networks:
      - jellyfin_default
    ports:
      - 5055:5055
    restart: unless-stopped
networks:
  jellyfin_default:
    external: true
