---
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      # - JELLYFIN_PublishedServerUrl= #optional
      - DOCKER_MODS=linuxserver/mods:jellyfin-amd
    volumes:
      - ${DOCKER_PERSISTENT_STORAGE_DIR}/jellyfin:/config
      - ${MEDIA_DIR}:/media
    networks:
      - default
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      # - 1900:1900/udp #optional
    devices:
      - /dev/dri:/dev/dri
      - /dev/kfd:/dev/kfd
    restart: unless-stopped
networks:
  default:
    driver: bridge
