---
version: "2.1"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=0
      - PGID=0
      - TZ=Etc/UTC
    volumes:
      - $HOME/.containers/jellyfin/config:/config
      - /media:/media
    ports:
      - 8096:8096
    restart: unless-stopped
