---
services:
  homarr:
    image: ghcr.io/ajnart/homarr:latest
    container_name: homarr
    environment:
      - DISABLE_ANALYTICS=true
      - DEFAULT_COLOR_SCHEME=dark
      - TZ=Etc/UTC
    volumes:
      - ${DOCKER_PERSISTENT_STORAGE_DIR}/homarr/configs:/app/data/configs
      - ${DOCKER_PERSISTENT_STORAGE_DIR}/homarr/data:/data
      - ${DOCKER_PERSISTENT_STORAGE_DIR}/homarr/icons:/app/public/icons
      - /var/run/docker.sock:/var/run/docker.sock #optional
    ports:
      - 80:7575
    restart: unless-stopped
