---
services:
  ownfoil:
    image: a1ex4/ownfoil
    container_name: ownfoil
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${DOCKER_PERSISTENT_STORAGE_DIR}/ownfoil:/app/config
      - ${GAMES_DIR}:/games
    ports:
      - 8465:8465
    restart: unless-stopped
